apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    chart: "{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: session-deployment
    spec:
      containers:
      - name: microservice-session
        image: {{ default "microservice-session:latest" .Values.image }}
        ports:
          - containerPort: 9080
        imagePullPolicy: IfNotPresent
        env:
{{ if ne .Values.test true }}         
          - name: MB_KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-keystore-password
                key: password
          - name: MB_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mb-truststore-password
                key: password
{{ end }}
        volumeMounts:
{{ if ne .Values.test true }}         
        - name: keystore
          mountPath: /etc/wlp/config/keystore
        - name: truststore
          mountPath: /etc/wlp/config/truststore
        - name: liberty-config
          mountPath: /config/configDropins
{{ end }}        
        readinessProbe:
          httpGet:
            path: /sessions/nessProbe
            port: 9080
          initialDelaySeconds: 10
          periodSeconds: 5
{{ if ne .Values.test true}} 
      volumes:
      - name: keystore
        secret:
          secretName: mb-keystore
      - name: truststore
        secret:
          secretName: mb-truststore
      - name: liberty-config
        configMap:
          name: liberty-logging-config
          items:
            - key: keystore.xml
              path: defaults/keystore.xml
            - key: logging.xml
              path: defaults/logging.xml
{{ end }}
---
apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  ports:
    - port: 9080
  selector:
    name: session-deployment
